### ISSUE TITLE
如何打包成桌面应用程序

### ISSUE THREAD

**Issue by ysun** [scraino/scraino-gui#2]
想请教一下，用什么方法打包的桌面应用程序。
以及，打包后的应用程序的串口，是如何工作的？
望大神指点一二。

**Comment by ghost** [comment]
用[electron](https://github.com/electron/electron)打包成桌面应用，串口用[node-serialport](https://github.com/serialport/node-serialport)

**Comment by ysun** [comment]
Hi Yahb,

我执行 electron . --no-sandbox    出现下面的错误。看上去没有生成dist，我也没有在package.json里面找到生成dist的脚本。
能否简单的指点一二 使用electron的具体打包过程，我可以帮忙更新repo，以及readme。

Error launching app                                                                          
Unable to find Electron app at /home/works/scratch3.0/scraino-gui                            
                                                                                             
Cannot find module '/home/scraino-gui/dist/scratch-gui.js'. Please verify that the package.json has a valid "main" entry

**Comment by ysun** [comment]
electron 这个东西对国内的网络真的是太不友好了，折腾了好几天，也没有build 出scratch-desktop.
想问下，能否使用nw.js打包，并且同样能够使用node-serialport ？

**Comment by ghost** [comment]
1. 首先添加 node.js 相关的国内镜像，将以下内容添加到 `~/.npmrc`
```
registry=https://repo.huaweicloud.com/repository/npm/
msvs_version=2015
disturl=https://repo.huaweicloud.com/nodejs
SASS_BINARY_SITE=https://repo.huaweicloud.com/node-sass
PHANTOMJS_CDNURL=https://repo.huaweicloud.com/phantomjs
CHROMEDRIVER_CDNURL=https://repo.huaweicloud.com/chromedriver
OPERADRIVER_CDNURL=https://repo.huaweicloud.com/operadriver
ELECTRON_MIRROR=https://repo.huaweicloud.com/electron/
PYTHON_MIRROR=https://repo.huaweicloud.com/python
PUPPETEER_DOWNLOAD_HOST=https://repo.huaweicloud.com
```

2. 在安装 scratch-desktop 的依赖前，先将 `package.json` 中 scratch-gui 依赖删掉，再 `npm i` ，然后按照 readme 中的步骤构建即可。

3. 可以用 nw.js 打包, nw.js 也能使用 node-serialport ，但你可以直接使用 [chrome.serial](https://developer.chrome.com/apps/serial) 代替 node-serialport

**Comment by ysun** [comment]
嗯，我再去试下看看。
另外问个小问题，你用什么Linux distribution？ 我用ubuntu 16.04， 用electron打包一个demo程序，win32的，提醒我安装wine，我装了64位的wine之后，说还需要安装32位的，装32位的wine的话，超级多32位的依赖库需要安装。你遇到这问题没？
我的参数这样的：
```
electron-packager . DesktopApp --platform=win32 --arch=x64 --out=dist --asar --electron-version=6.0.1 --download.cacheRoot=/tmp/ --overwrite
```

**Comment by ysun** [comment]
我觉得nw.js的方式，稍微容易理解一点。只是，我用nw.js运行scraino，有两个问题：
1. 串口好像不工作，发现不了串口
2. 点击左下角那个添加扩展的按钮，以及右上角切换舞台的时候，显示蓝色的错误消息“Oops! Something went wrong.”

如果，scraino可以使用nw.js打包，让串口工作起来的话，果断放弃折腾electron。
这个实际中你们用nw.js打包过没？

**Comment by ghost** [comment]
1. 使用 winodws10 构建，这个项目主要对象是中小学生，没有考虑 linux 版本，如果你用 linux 系统，我建议使用 CI ，[Travis CI](https://travis-ci.com/) 和 [AppVeyor](https://www.appveyor.com/) 都能构建 windows 应用。
2. 串口不能工作是因为这个项目中不包含串口部分，需要自己完成或等待 scraino 上传主进程的代码。
3. 显示错误是因为这个项目是针对 electron 写的，nw.js 和 electron 还是不一样的，不能直接使用。
4. scraino 最早使用的就是 nw.js ，因为 nw.js 制作发行安装包不方便，后来才转到 electron 。

**Comment by ysun** [comment]
1. 我无所谓用啥OS构建，Linux 或者 win10都可以，想着只要能打包就好了。那我接下来在win10上试下。
2. 没有包含串口部分——这有点小遗憾。scraino会有计划上传“主进程”代码吗？我对JS或者chrome开发没有特别专业，自己捣鼓的话可能难度比较大。如果可以，期待scraino可以open source包含串口的代码。
3. 如果可以，方便加个微信吗？  我的: syqust
非常感谢您的时间！
